### ISSUE TITLE
AndroidX new auth0Client Adds a slash at the end of the Issuer and causes a mismatch exception

### ISSUE THREAD

**Issue by Crorpa** [auth0/auth0-oidc-client-net#330]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-oidc-client-net#readme) and the [documentation](https://auth0.github.io/auth0-oidc-client-net/documentation/intro.html), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-oidc-client-net/api/Auth0.OidcClient.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-oidc-client-net/issues) and have not found a suitable solution or answer.
- [x] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When doing Login Async on Xamarin (Android) using AndroidX nugget it return an exception: Issuer (iss) claim mismatch in the ID token; expected "https://domain/", found "https://domain".

I can see this Issuer at Auth0client/base/Non_public members/_idtokenRequirements/Issuer

It seems that instantiating auth0client adds a slash at the end of Issuer, because I put the domain without that slash.

### Reproduction

Follow Auth0.oidclient.AndroidX guide, this for example:

https://auth0.com/docs/quickstart/native/net-android-ios/interactive

### auth0-oidc-client-net version

AndroiX 4.0.0

### .NET version

.Net Standard 2.1

### Platform

Android

### Platform version(s)

13.0

**Comment by AliKarimiENT** [comment]
I have faced the same issue

**Comment by AliKarimiENT** [comment]
My exception is as the blow:
`Auth0.OidcClient.Tokens.IdTokenValidationException: Issuer (iss) claim mismatch in the ID token; expected "https://Domain/", found "https://Domain".
   at Auth0.OidcClient.Tokens.IdTokenValidator.AssertTokenClaimsMeetRequirements(IdTokenRequirements required, JwtSecurityToken token, DateTime pointInTime)
   at Auth0.OidcClient.Tokens.IdTokenValidator.AssertTokenMeetsRequirements(IdTokenRequirements required, String rawIDToken, Nullable`1 pointInTime, ISignatureVerifier signatureVerifier)
   at Auth0.OidcClient.Auth0ClientBase.LoginAsync(Object extraParameters, CancellationToken cancellationToken)
   at BobThePhysio.Mobile.Infrastructure.Services.AuthorizationService.LoginAsync() in /Users/alikarimi/Projects/BobDePhisio/src/BobThePhysio.Mobile.Infrastructure/Services/AuthorizationService.cs:line 27`

**Comment by frederikprijck** [comment]
Can you elaborate what the issuer is?
As far as i know, with auth0, the issuer always has a trailing slash, and the issuer is expected to be https://domain/.

If you are using another identity provider, and not auth0, please know this is designed to only work with auth0. If you use a different identity provider, you should be fine just using IdentityModel.OidcClient like we use under the hood.

**Comment by AliKarimiENT** [comment]
@Crorpa After trying many times, I decided to stop using it because of poor support and switched to using the OidcClient nuget package instead. It works well and I was also able to display it as a WebView, and the configuration works there too.

**Comment by dimadsen** [comment]
> Can you elaborate what the issuer is? As far as i know, with auth0, the issuer always has a trailing slash, and the issuer is expected to be https://domain/.
> 
> Are you saying your issuer with auth0 does not have a trailing slash?
> 
> If you are using another identity provider, and not auth0, please know this is designed to only work with auth0. If you use a different identity provider, you should be fine just using IdentityModel.OidcClient like we use under the hood.

even in the documentation there is no slash https://openid.net/specs/openid-connect-core-1_0.html#IDToken
